-- Drop indexes
DROP INDEX IF EXISTS idx_player_leagues;
DROP INDEX IF EXISTS idx_battle_logs_defender;
DROP INDEX IF EXISTS idx_battle_logs_attacker;

-- Drop tables
DROP TABLE IF EXISTS battle_replays CASCADE;
DROP TABLE IF EXISTS battles CASCADE;
DROP TABLE IF EXISTS base_snapshots CASCADE;
DROP TABLE IF EXISTS base_layouts CASCADE;
DROP TABLE IF EXISTS game_state CASCADE;
DROP TABLE IF EXISTS user_items CASCADE;
DROP TABLE IF EXISTS items_limits CASCADE;
DROP TABLE IF EXISTS items CASCADE;
DROP TABLE IF EXISTS user_combat CASCADE;
DROP TABLE IF EXISTS user_economy CASCADE;
DROP TABLE IF EXISTS user_stats CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS auth CASCADE;

-- Drop enums
DROP TYPE IF EXISTS currency_type;
DROP TYPE IF EXISTS item_category;

-- Drop extensions
DROP EXTENSION IF EXISTS pgcrypto;
