ALTER TABLE troops DROP COLUMN IF EXISTS hp;
ALTER TABLE troops DROP COLUMN IF EXISTS dps;
ALTER TABLE troops DROP COLUMN IF EXISTS speed;
ALTER TABLE troops DROP COLUMN IF EXISTS attack_range;
ALTER TABLE troops DROP COLUMN IF EXISTS preferred_target;

ALTER TABLE building_levels DROP COLUMN IF EXISTS attack_range;
