ALTER TABLE troops ADD COLUMN IF NOT EXISTS hp INT NOT NULL DEFAULT 100;
ALTER TABLE troops ADD COLUMN IF NOT EXISTS dps INT NOT NULL DEFAULT 10;
ALTER TABLE troops ADD COLUMN IF NOT EXISTS speed FLOAT NOT NULL DEFAULT 1.0;
ALTER TABLE troops ADD COLUMN IF NOT EXISTS attack_range FLOAT NOT NULL DEFAULT 1.5;
ALTER TABLE troops ADD COLUMN IF NOT EXISTS preferred_target TEXT NOT NULL DEFAULT 'any';

ALTER TABLE building_levels ADD COLUMN IF NOT EXISTS attack_range FLOAT NOT NULL DEFAULT 0;

UPDATE building_levels SET attack_range = 5.0
WHERE building_id = 'angel-spire';
